### ISSUE TITLE
Log.v irregularity

### ISSUE THREAD

**Issue by grebulon** [dpreussler/jodamoblog#1]
In Log.java, the first v() method is calling android.util.Log.v(), while all the other methods call on the logger instance.
Bug?

**Comment by dpreussler** [comment]
thanks for pointing to that. Is a bug of course.
I changed it. I would not build a new version for that but in case you need it, let me know

**Comment by grebulon** [comment]
Not needed. I will fork as I'm adding a few features, like seeing the level separately for each receiver, specially the file target.
